name: pastiin_mobile_app
description: pastiin  mobile app

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.10.1 <3.0.0"

dependencies:
  alice: ^0.2.5
  another_flushbar: ^1.10.26
  bloc_concurrency: ^0.2.0
  cached_network_image: ^3.2.0
  carousel_slider: ^4.0.0
  clipboard: ^0.1.3
  connectivity_plus: ^2.1.0
  cupertino_icons: ^1.0.2
  dio: ^4.0.4
  fast_immutable_collections: ^7.0.3
  firebase_analytics: ^9.0.4
  firebase_core: ^1.10.6
  firebase_messaging: ^11.2.4
  firebase_remote_config: ^2.0.0
  flutter:
    sdk: flutter
  flutter_animated_dialog: ^2.0.1
  flutter_bloc: ^8.0.1
  flutter_datetime_picker: ^1.5.1
  flutter_hooks: ^0.18.1
  flutter_html: ^2.2.1
  flutter_rating_bar: ^4.0.0
  flutter_secure_storage: ^5.0.2
  flutter_sticky_header: ^0.6.0
  flutter_svg: ^0.22.0
  fpdart: ^0.0.12
  freezed_annotation: ^1.0.0
  get_it: ^7.2.0
  grouped_list: ^4.1.0
  hive_flutter: ^1.1.0
  injectable: ^1.5.0
  intl: ^0.17.0
  json_annotation: ^4.4.0
  lottie: ^1.2.1
  material_design_icons_flutter: ^5.0.6595
  modal_bottom_sheet: ^2.0.0
  package_info_plus: ^1.3.0
  percent_indicator: ^4.0.0
  pin_code_fields: ^7.3.0
  pull_to_refresh: ^2.0.0
  scroll_app_bar: ^2.0.0
  shimmer: ^2.0.0
  smooth_page_indicator: ^1.0.0+2
  table_calendar: ^3.0.3
  url_launcher: ^6.0.18
  uuid: ^3.0.5
  webview_flutter: ^2.0.4

dev_dependencies:
  auto_route_generator: ^3.1.0
  build_runner: ^2.1.5
  flutter_launcher_icons: ^0.9.2
  flutter_lints: ^1.0.0
  flutter_test:
    sdk: flutter
  freezed: ^1.0.2
  injectable_generator: ^1.5.2
  json_serializable: ^6.1.1
  lint: ^1.7.2
  logger: ^1.1.0
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
